name: playwith_customer_app
description: ""
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  settings_ui: ^2.0.2
  percent_indicator: ^4.0.0
  provider: ^6.0.2
  flutter_native_timezone_updated_gradle: ^2.0.3
  rxdart: ^0.27.3
  circular_countdown_timer: ^0.2.0
  shared_preferences: 2.0.13
  flutter_local_notifications: ^9.3.2

  cupertino_icons: ^1.0.2
  audioplayers: ^6.0.0
  # TODO(Peu):
  url_launcher: ^6.1.4
  logger: ^2.3.0
  sign_in_button: ^3.2.0
  font_awesome_flutter: ^10.1.0
  auto_size_text: ^3.0.0
  flutter_animate: ^4.1.1+1
  
  google_mobile_ads: ^5.1.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  # google_sign_in_web: ^0.12.4+1
  firebase_analytics: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/