import 'package:playwith_customer_app/core/i18n/strings/i18n_strings.dart';
import 'package:playwith_customer_app/lessons_and_quizzes/question.dart';

import '../components/sheet_music_components/note.dart';

/// A list of all of the questions in the app
final List<Question> questions = [
  Question(
    clef: Clef.treble,
    question: I18n.strings.question1,
    correctAnswer: Note(name: 'C4'),
    questionID: 1,
    lessonID: 1,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.question2,
    correctAnswer: Note(name: 'D4'),
    questionID: 2,
    lessonID: 1,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.question3,
    correctAnswer: Note(name: 'E4'),
    questionID: 3,
    lessonID: 1,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.question4,
    correctAnswer: Note(name: 'C4'),
    questionID: 4,
    lessonID: 1,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D4'),
    questionID: 5,
    lessonID: 1,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'E4'),
    questionID: 6,
    lessonID: 1,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D4'),
    questionID: 7,
    lessonID: 1,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'E4'),
    questionID: 8,
    lessonID: 1,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C4'),
    questionID: 9,
    lessonID: 1,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'E4'),
    questionID: 10,
    lessonID: 1,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C4'),
    questionID: 11,
    lessonID: 1,
  ),

  /// Lesson 2
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson2Introduction,
    correctAnswer: Note(name: 'F4'),
    questionID: 12,
    lessonID: 2,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson2GNote,
    correctAnswer: Note(name: 'G4'),
    questionID: 13,
    lessonID: 2,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson2Practice,
    correctAnswer: Note(name: 'G4'),
    questionID: 14,
    lessonID: 2,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F4'),
    questionID: 15,
    lessonID: 2,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'G4'),
    questionID: 16,
    lessonID: 2,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'E4'),
    questionID: 17,
    lessonID: 2,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D4'),
    questionID: 18,
    lessonID: 2,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F4'),
    questionID: 19,
    lessonID: 2,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C4'),
    questionID: 20,
    lessonID: 2,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'E4'),
    questionID: 21,
    lessonID: 2,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F4'),
    questionID: 22,
    lessonID: 2,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'G4'),
    questionID: 23,
    lessonID: 2,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F4'),
    questionID: 24,
    lessonID: 2,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'G4'),
    questionID: 25,
    lessonID: 2,
  ),

  ///Lesson 3
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson3Introduction,
    correctAnswer: Note(name: 'A4'),
    questionID: 26,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson3BNote,
    correctAnswer: Note(name: 'B4'),
    questionID: 27,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson3Practice,
    correctAnswer: Note(name: 'B4'),
    questionID: 28,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'A4'),
    questionID: 29,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'G4'),
    questionID: 30,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'B4'),
    questionID: 31,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F4'),
    questionID: 32,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'B4'),
    questionID: 33,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'A4'),
    questionID: 34,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'E4'),
    questionID: 35,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D4'),
    questionID: 36,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'A4'),
    questionID: 37,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C4'),
    questionID: 38,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D4'),
    questionID: 39,
    lessonID: 3,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'E4'),
    questionID: 40,
    lessonID: 3,
  ),

  ///Lesson 4
  Question(
    clef: Clef.bass,
    question: I18n.strings.lesson4Introduction,
    correctAnswer: Note(name: 'C3'),
    questionID: 41,
    lessonID: 4,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.lesson4DNote,
    correctAnswer: Note(name: 'D3'),
    questionID: 42,
    lessonID: 4,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.lesson4ENote,
    correctAnswer: Note(name: 'E3'),
    questionID: 43,
    lessonID: 4,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.lesson4FNote,
    correctAnswer: Note(name: 'F3'),
    questionID: 44,
    lessonID: 4,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.lesson4Practice,
    correctAnswer: Note(name: 'E3'),
    questionID: 45,
    lessonID: 4,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D3'),
    questionID: 46,
    lessonID: 4,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F3'),
    questionID: 47,
    lessonID: 4,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C3'),
    questionID: 48,
    lessonID: 4,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D3'),
    questionID: 49,
    lessonID: 4,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'E3'),
    questionID: 50,
    lessonID: 4,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C3'),
    questionID: 51,
    lessonID: 4,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F3'),
    questionID: 52,
    lessonID: 4,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C3'),
    questionID: 53,
    lessonID: 4,
  ),

  ///Lesson 5
  Question(
    clef: Clef.bass,
    question: I18n.strings.lesson5Introduction,
    correctAnswer: Note(name: 'G3'),
    questionID: 54,
    lessonID: 5,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.lesson5ANote,
    correctAnswer: Note(name: 'A3'),
    questionID: 55,
    lessonID: 5,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.lesson5BNote,
    correctAnswer: Note(name: 'B3'),
    questionID: 56,
    lessonID: 5,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.lesson5Practice,
    correctAnswer: Note(name: 'A3'),
    questionID: 57,
    lessonID: 5,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'B3'),
    questionID: 58,
    lessonID: 5,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'G3'),
    questionID: 59,
    lessonID: 5,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C3'),
    questionID: 60,
    lessonID: 5,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D3'),
    questionID: 61,
    lessonID: 5,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F3'),
    questionID: 62,
    lessonID: 5,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'A3'),
    questionID: 63,
    lessonID: 5,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'G3'),
    questionID: 64,
    lessonID: 5,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'B3'),
    questionID: 65,
    lessonID: 5,
  ),

  /// Lesson 6
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson6Introduction,
    correctAnswer: Note(name: 'B4'),
    questionID: 66,
    lessonID: 6,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson6CNote,
    correctAnswer: Note(name: 'C5'),
    questionID: 67,
    lessonID: 6,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson6Practice,
    correctAnswer: Note(name: 'B4'),
    questionID: 68,
    lessonID: 6,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C5'),
    questionID: 69,
    lessonID: 6,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D5'),
    questionID: 70,
    lessonID: 6,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'E5'),
    questionID: 71,
    lessonID: 6,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'A4'),
    questionID: 72,
    lessonID: 6,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C5'),
    questionID: 73,
    lessonID: 6,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D5'),
    questionID: 74,
    lessonID: 6,
  ),

  ///Lesson 7
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson7Introduction,
    correctAnswer: Note(name: 'C4'),
    questionID: 75,
    lessonID: 7,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson7BNote,
    correctAnswer: Note(name: 'B3'),
    questionID: 76,
    lessonID: 7,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson7Practice,
    correctAnswer: Note(name: 'A3'),
    questionID: 77,
    lessonID: 7,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'B3'),
    questionID: 78,
    lessonID: 7,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'A3'),
    questionID: 79,
    lessonID: 7,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D4'),
    questionID: 80,
    lessonID: 7,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'B3'),
    questionID: 81,
    lessonID: 7,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C4'),
    questionID: 82,
    lessonID: 7,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'A3'),
    questionID: 83,
    lessonID: 7,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'B3'),
    questionID: 84,
    lessonID: 7,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C4'),
    questionID: 85,
    lessonID: 7,
  ),

  ///Lesson 8
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson8Introduction,
    correctAnswer: Note(name: 'F#4'),
    questionID: 86,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson8FlatNote,
    correctAnswer: Note(name: 'Bb4'),
    questionID: 87,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson8Practice,
    correctAnswer: Note(name: 'F#4'),
    questionID: 88,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'G4'),
    questionID: 89,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C4'),
    questionID: 90,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C#4'),
    questionID: 91,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D4'),
    questionID: 92,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'E4'),
    questionID: 93,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F#4'),
    questionID: 94,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'B4'),
    questionID: 95,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'Bb4'),
    questionID: 96,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'A4'),
    questionID: 97,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'Ab4'),
    questionID: 98,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'A4'),
    questionID: 99,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'Bb4'),
    questionID: 100,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'Eb4'),
    questionID: 101,
    lessonID: 8,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'G#4'),
    questionID: 102,
    lessonID: 8,
  ),

  ///Lesson 9
  Question(
    clef: Clef.treble,
    question: I18n.strings.lesson9Introduction,
    correctAnswer: Note(name: 'C4'),
    questionID: 103,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F4'),
    questionID: 104,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F#4'),
    questionID: 105,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'G4'),
    questionID: 106,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C#4'),
    questionID: 107,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D4'),
    questionID: 108,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'A3'),
    questionID: 109,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'Bb3'),
    questionID: 110,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'B3'),
    questionID: 111,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'G#4'),
    questionID: 112,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'A4'),
    questionID: 113,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'Ab4'),
    questionID: 114,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'Eb4'),
    questionID: 115,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F#4'),
    questionID: 116,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'Bb4'),
    questionID: 117,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'B4'),
    questionID: 118,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C5'),
    questionID: 119,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'E5'),
    questionID: 120,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'Db5'),
    questionID: 121,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F5'),
    questionID: 122,
    lessonID: 9,
  ),
  Question(
    clef: Clef.treble,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D5'),
    questionID: 123,
    lessonID: 9,
  ),

  ///Lesson 10
  Question(
    clef: Clef.bass,
    question: I18n.strings.lesson10Introduction,
    correctAnswer: Note(name: 'C3'),
    questionID: 124,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'E3'),
    questionID: 125,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'Db3'),
    questionID: 126,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C#3'),
    questionID: 127,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'A3'),
    questionID: 128,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'C4'),
    questionID: 129,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'G3'),
    questionID: 130,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F#3'),
    questionID: 131,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D#3'),
    questionID: 132,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'F3'),
    questionID: 133,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'D3'),
    questionID: 134,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'Eb3'),
    questionID: 135,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'B3'),
    questionID: 136,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'Bb3'),
    questionID: 137,
    lessonID: 10,
  ),
  Question(
    clef: Clef.bass,
    question: I18n.strings.whatNoteIsThis,
    correctAnswer: Note(name: 'G#3'),
    questionID: 138,
    lessonID: 10,
  ),
];
