// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyZb8ggiNo_fSXZgmZNwV27Z13Lp1iHD4',
    appId: '1:887207760977:web:2f60e95464548a5d7e5470',
    messagingSenderId: '887207760977',
    projectId: 'playwith-customer-app',
    authDomain: 'playwith-customer-app.firebaseapp.com',
    storageBucket: 'playwith-customer-app.appspot.com',
    measurementId: 'G-6MNP1J3PJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvngZqJk9XAY-YgLlHJMoY3i_96pbcZBE',
    appId: '1:887207760977:android:3b9f046c8535cc5f7e5470',
    messagingSenderId: '887207760977',
    projectId: 'playwith-customer-app',
    storageBucket: 'playwith-customer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnc7LjtDrhDPCH5Oh0VnUwh8sxFa56_GU',
    appId: '1:887207760977:ios:a6f21f019aa649a77e5470',
    messagingSenderId: '887207760977',
    projectId: 'playwith-customer-app',
    storageBucket: 'playwith-customer-app.appspot.com',
    androidClientId: '887207760977-3khq4a5d6ct1rnu5kl2k294b4o863s7t.apps.googleusercontent.com',
    iosClientId: '887207760977-65ksl3b6eu6qltqb57t961rfnprackq4.apps.googleusercontent.com',
    iosBundleId: 'br.com.playwith.playwithCustomerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnc7LjtDrhDPCH5Oh0VnUwh8sxFa56_GU',
    appId: '1:887207760977:ios:a6f21f019aa649a77e5470',
    messagingSenderId: '887207760977',
    projectId: 'playwith-customer-app',
    storageBucket: 'playwith-customer-app.appspot.com',
    androidClientId: '887207760977-3khq4a5d6ct1rnu5kl2k294b4o863s7t.apps.googleusercontent.com',
    iosClientId: '887207760977-65ksl3b6eu6qltqb57t961rfnprackq4.apps.googleusercontent.com',
    iosBundleId: 'br.com.playwith.playwithCustomerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyZb8ggiNo_fSXZgmZNwV27Z13Lp1iHD4',
    appId: '1:887207760977:web:74e13521be6b4bb57e5470',
    messagingSenderId: '887207760977',
    projectId: 'playwith-customer-app',
    authDomain: 'playwith-customer-app.firebaseapp.com',
    storageBucket: 'playwith-customer-app.appspot.com',
    measurementId: 'G-DRFRG2KY8X',
  );
}
